#!/usr/bin/env python3
"""Generate go2rtc.yaml for the go2rtc-hik sidecar from cameras.json.

Same private config as the dashboard generator (dashboards/cameras.json):

  h264 camera -> hik_cam_<id>:  direct exec bridge
  h265 camera -> hik_cam_<id>_src: exec bridge (raw HEVC) +
                 hik_cam_<id>: ffmpeg#video=h264 wrapper for browsers

go2rtc gotchas encoded here (see README):
  - stream sources must be single-line QUOTED strings (`- "exec: …"`);
    map form is silently dropped, folded `>` scalars produce empty commands
  - no `#audio=none` — go2rtc's ffmpeg template passes it as the output
    filename (bridge streams are video-only anyway)

Usage:
    python3 generate_go2rtc.py out-go2rtc.yaml [--cameras cameras.json]
"""

from __future__ import annotations

import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))

HEADER = """\
# GENERATED by deploy/generate_go2rtc.py from cameras.json — do not edit.
#
# Credentials come from the environment (HIK_URL/HIK_USER/HIK_PASS in the
# stack .env — same values as the HA hikcentral_district config entry).
# The whole integration dir is bind-mounted to /app/bridge; streams spawn
# on demand (go2rtc starts the exec per viewer and stops it on disconnect).
#
# HA 2026.6 bundles only a go2rtc *client* (`go2rtc: streams:` YAML is
# rejected in configuration.yaml) — run this config in a standalone go2rtc
# (see docker-compose.example.yaml) and point the integration's
# stream_url_template at rtsp://127.0.0.1:18556/hik_cam_{id}.

log:
  level: info

rtsp:
  # loopback v4 only: HA (host network) reads the stream from 127.0.0.1.
  # HA-managed go2rtc owns :18554 (rtsp) and :18555 (webrtc, v6 wildcard).
  listen: "127.0.0.1:18556"

api:
  # local debug API only
  listen: "127.0.0.1:1984"

streams:
"""

EXEC_TPL = (
    '    - "exec: python3 /app/bridge/rtsp_bridge.py '
    '--host ${{HIK_URL}} --username ${{HIK_USER}} --password ${{HIK_PASS}} '
    '--camera {cid} --insecure"'
)


def main() -> None:
    args = sys.argv[1:]
    cameras_path = args[args.index("--cameras") + 1] if "--cameras" in args else None
    path = cameras_path or os.path.join(HERE, "..", "dashboards", "cameras.json")
    if not os.path.isfile(path):
        sys.exit(
            f"cameras config not found: {path}\n"
            "Copy dashboards/cameras.example.json -> dashboards/cameras.json "
            "and fill in YOUR cameras (the file is gitignored)."
        )
    out = args[0] if args and not args[0].startswith("--") else "/dev/stdout"
    cfg = json.load(open(path, encoding="utf-8"))
    lines = [HEADER]
    for c in cfg.get("cameras", []):
        cid = str(c["id"])
        codec = (c.get("codec") or "h264").lower()
        if codec == "h265":
            lines.append(f"  hik_cam_{cid}_src:")
            lines.append(EXEC_TPL.format(cid=cid))
            lines.append(f"  hik_cam_{cid}:")
            lines.append(
                f'    - "ffmpeg:rtsp://127.0.0.1:18556/hik_cam_{cid}_src#video=h264"'
            )
        else:
            lines.append(f"  hik_cam_{cid}:")
            lines.append(EXEC_TPL.format(cid=cid))
    with open(out, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")
    print(f"go2rtc config written: {out} ({len(cfg.get('cameras', []))} cameras)")


if __name__ == "__main__":
    main()
